# Generated by Django 3.0.6 on 2020-06-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200629_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='requeted',
            new_name='requested',
        ),
    ]
